name: cstar_env
channels:
  - conda-forge
dependencies:
  - ipykernel
  - jupyterlab
  - netCDF4
  - numpy>2.0,<2.4  # currently numba doesn't support 2.4
  - pip
  - python>=3.10,<3.14
  - xarray
  - roms-tools>=3.5,<4
  # only needed for building docs
  - pandoc
