name: cstar_env
channels:
  - conda-forge
dependencies:
  - compilers
  - ipykernel
  - jupyterlab
  - mpich
  - netCDF4
  - netcdf-fortran
  - numpy>2.0,<2.4
  - pip
  - python>=3.10,<3.14
  - roms-tools>=3.5,<4
  - rsync
  - xarray
  # only needed for building docs
  - pandoc
